package com.tj.dao;

import com.tj.pojo.Order;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tj_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tj_order
     *
     * @mbg.generated
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tj_order
     *
     * @mbg.generated
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tj_order
     *
     * @mbg.generated
     */
    List<Order> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tj_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Order record);
    /*
    * 根据userId和orderNo查询订单
    * */
    Order findOrderByUserIdAndOrderNo(@Param("userId") Integer userId,
                                      @Param("orderNo") Long orderNo);

    /*
    * 按照用户ID查询订单
    * */
    List<Order> findOrderByUserId(Integer userId);
    /*
    * 根据订单号查询
    * */
    Order findOrderByOrderNo(Long orderNo);
    /*
    * 根据订单创建时间查找未付款订单
    * */
    List<Order> findOrderByCreateTime(@Param("date") String date,
                                      @Param("status") Integer status);
}