package com.tj.dao;

import com.tj.pojo.Category;
import com.tj.pojo.Product;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Set;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tj_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tj_product
     *
     * @mbg.generated
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tj_product
     *
     * @mbg.generated
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tj_product
     *
     * @mbg.generated
     */
    List<Product> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tj_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Product record);
    /*
    * 更新商品状态
    * */
    Integer updateProductKeySelective(Product product);
    /*
    * 通过productId或者productName查询商品
    * */
    List<Product> findProductByProductIdAndProductName(@Param("productId")Integer productId,
                                                       @Param("productName") String productName);
    /*
    * 通过类别id或者keyword查询商品
    * */
    List<Product> searchProduct(@Param("categoryIdList") Set<Integer> categoryIdList,
                                @Param("keyword") String keyword);
    /*
    * 根据商品ID查库存
    * */
    Integer findStockById(Integer productId);
}