package com.tj.dao;

import com.tj.pojo.Category;
import com.tj.pojo.Product;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tj_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tj_product
     *
     * @mbg.generated
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tj_product
     *
     * @mbg.generated
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tj_product
     *
     * @mbg.generated
     */
    List<Product> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tj_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Product record);
    /*
    * 更新商品状态
    * */
    int updateProductKeySelective(Product product);
    /*
    * 通过productId或者productName查询商品
    * */
    List<Product> findProductByProductIdAndProductName(@Param(value = "productId")Integer productId,
                                                       @Param(value="productName") String productName);

}