package com.tj.dao;

import com.tj.pojo.Shipping;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ShippingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tj_shipping
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tj_shipping
     *
     * @mbg.generated
     */
    int insert(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tj_shipping
     *
     * @mbg.generated
     */
    Shipping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tj_shipping
     *
     * @mbg.generated
     */
    List<Shipping> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tj_shipping
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Shipping record);
    /*
    * 删除地址（防止横向越权，用userId和shippingId组合）
    * */
    int deleteByUserIdAndShippingId(@Param("userId") Integer userId,
                                    @Param("shipping")Integer shipping);
    /*
    * 更新地址表
    * */
    int updateBySelectiveKey(Shipping shipping);
}