package com.tj.vo;

import java.io.Serializable;

public class ShippingVO implements Serializable {
    private String receiverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tj_shipping.receiver_phone
     *
     * @mbg.generated
     */
    private String receiverPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tj_shipping.receiver_mobile
     *
     * @mbg.generated
     */
    private String receiverMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tj_shipping.receiver_provice
     *
     * @mbg.generated
     */
    private String receiverProvice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tj_shipping.receiver_city
     *
     * @mbg.generated
     */
    private String receiverCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tj_shipping.receiver_district
     *
     * @mbg.generated
     */
    private String receiverDistrict;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tj_shipping.receiver_address
     *
     * @mbg.generated
     */
    private String receiverAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tj_shipping.receiver_zip
     *
     * @mbg.generated
     */
    private String receiverZip;

    public String getReceiverName() {
        return receiverName;
    }

    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName;
    }

    public String getReceiverPhone() {
        return receiverPhone;
    }

    public void setReceiverPhone(String receiverPhone) {
        this.receiverPhone = receiverPhone;
    }

    public String getReceiverMobile() {
        return receiverMobile;
    }

    public void setReceiverMobile(String receiverMobile) {
        this.receiverMobile = receiverMobile;
    }

    public String getReceiverProvice() {
        return receiverProvice;
    }

    public void setReceiverProvice(String receiverProvice) {
        this.receiverProvice = receiverProvice;
    }

    public String getReceiverCity() {
        return receiverCity;
    }

    public void setReceiverCity(String receiverCity) {
        this.receiverCity = receiverCity;
    }

    public String getReceiverDistrict() {
        return receiverDistrict;
    }

    public void setReceiverDistrict(String receiverDistrict) {
        this.receiverDistrict = receiverDistrict;
    }

    public String getReceiverAddress() {
        return receiverAddress;
    }

    public void setReceiverAddress(String receiverAddress) {
        this.receiverAddress = receiverAddress;
    }

    public String getReceiverZip() {
        return receiverZip;
    }

    public void setReceiverZip(String receiverZip) {
        this.receiverZip = receiverZip;
    }
}
